name: Build and Deploy Node.js to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'  # Specify your Node.js version here

      # Install dependencies and build the app
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build --if-present  # Optional, if you have a build step

      # Upload build artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: '.'  # Adjust the path to include only necessary build files

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the deploy job runs after the build job

    steps:
      # Download build artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: product-management-ctse # Replace with your App Service name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.'  # Deploy from the root directory of your repository

      # Verify deployment
      - name: Verify Deployment
        run: |
          curl -I https://product-management-ctse-cpepa7d9f0ahatfc.southindia-01.azurewebsites.net


