# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       # Checkout the repository
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Set up Docker Buildx
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       # Login to Docker Hub
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       # Build Docker image
#       - name: Build Docker image
#         run: |
#           docker build -t saarakaizerr/ctse-assignment:v1.0 .

#       # Push Docker image to Docker Hub
#       - name: Push Docker image to Docker Hub
#         run: |
#           docker push saarakaizerr/ctse-assignment:v1.0

#       # Deploy (Optional)
#       - name: Deploy (Optional)
#         if: github.ref == 'refs/heads/main'
#         run: |
#           docker run -d -p 3001:3001 saarakaizerr/ctse-assignment:v1.0



name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write   # Required for OIDC login
  contents: read    # Required to checkout the code

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Azure login using OIDC
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: SERVICE_PRINCIPAL

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ctseregistry.azurecr.io/ctse-assignment:v1.0 .

      # Login to ACR using Managed Identity
      - name: Login to ACR with Managed Identity
        run: |
          az acr login --name ctseregistry --expose-token

      # Push Docker image to ACR
      - name: Push Docker image to ACR
        run: |
          docker push ctseregistry.azurecr.io/ctse-assignment:v1.0

      # Optional: Deploy container or restart Container App
      - name: Restart Azure Container App (Optional)
        run: |
          az containerapp revision activate --name product-management-ctse --resource-group ctse-rg-new

