name: Build and Deploy to Azure Container Apps with ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ctseregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ctseregistry.azurecr.io/ctse-assignment:v1.3
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name product-management-ctse \
            --resource-group ctse-rg-new \
            --image ctseregistry.azurecr.io/ctse-assignment:v1.3 \
            --set-env-vars "MONGODB_URI=mongodb+srv://saara:saara@ctse.tjef4ed.mongodb.net/ctse?retryWrites=true&w=majority&appName=ctse"
  