name: Build, Scan for Vulnerabilities, and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ctseregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ctseregistry.azurecr.io/ctse-assignment:v1.3
          cache-from: type=gha
          cache-to: type=gha,mode=max

  snyk-scan:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: |
          npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_API_TOKEN }}

      - name: Test for Vulnerabilities
        continue-on-error: true
        run: snyk test --all-projects

  deploy:
    runs-on: ubuntu-latest
    needs: snyk-scan  # This ensures the deploy job will run only if snyk-scan passes

    steps:
      - name: Log in to Azure using Azure CLI
        run: |
          echo "Logging in to Azure using the Subscription and Tenant..."
          az login --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure Container Apps
        run: |
          echo "Deploying to Azure Container Apps..."
          az containerapp update \
            --name product-management-ctse \
            --resource-group ctse-rg-new \
            --image ctseregistry.azurecr.io/ctse-assignment:v1.3 \
            --set-env-vars "MONGODB_URI=mongodb+srv://saara:saara@ctse.tjef4ed.mongodb.net/ctse?retryWrites=true&w=majority&appName=ctse"
