name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t saarakaizerr/ctse-assignment:v1.0 .
          docker push saarakaizerr/ctse-assignment:v1.0

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name product-management-ctse \
            --resource-group ctse-rg1 \
            --image saarakaizerr/ctse-assignment:v1.0 \
            --set-env-vars "MONGODB_URI=${{ secrets.MONGODB_URI }}"

      - name: Verify Deployment
        run: |
          sleep 30
          curl -I https://product-management-ctse.southindia-01.azurecontainerapps.io